[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

# run game with  : cargo run --target wasm32-unknown-unknown
# generate files : cargo build --release --target wasm32-unknown-unknown wasm-bindgen --out-dir ./out/ --target web ./target/

# this first! : cargo build --release --target wasm32-unknown-unknown
# use this!   : wasm-bindgen --out-dir ./web/ --target web ./target/wasm32-unknown-unknown/release/bevy_jam_2.wasm